[project]
name = "dashboard" # required

[tool.pytest.ini_options]
testpaths = "home"
addopts = [
    "--ds=pytestplaywrightproject.settings.testing",
    # https://github.com/pytest-dev/pytest-django/issues/1062#issuecomment-1912865598
    "--create-db",
]
